# Generated by Django 4.1.6 on 2023-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.IntegerField(max_length=1),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slots',
            field=models.ManyToManyField(to='meet.timeslot'),
        ),
    ]
