# Generated by Django 4.1.6 on 2023-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_timeslot_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.IntegerField(),
        ),
    ]
