# Generated by Django 4.1.6 on 2023-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
