# Generated by Django 4.1.6 on 2023-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
