# Generated by Django 4.1.6 on 2023-06-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_timeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='room',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot',
            field=models.CharField(max_length=2),
        ),
    ]
