# Generated by Django 4.1.6 on 2023-06-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_alter_booking_room_alter_timeslot_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
