# Generated by Django 4.1.6 on 2023-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0008_alter_timeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
