# Generated by Django 4.1.6 on 2023-06-20 18:24

from django.db import migrations, models
import meet.models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_alter_timeslot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='id',
            field=models.CharField(default=meet.models.generate_unique_id, max_length=30, primary_key=True, serialize=False),
        ),
    ]
