# Generated by Django 4.1.6 on 2023-06-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_alter_timeslot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubatee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('bookings', models.ManyToManyField(to='meet.booking')),
            ],
        ),
    ]
