# Generated by Django 4.1.6 on 2023-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0012_alter_incubatee_options_alter_incubatee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
