# Generated by Django 4.1.6 on 2023-06-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0014_rename_timeslot_atimeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incubatee',
            name='bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
