# Generated by Django 4.1.6 on 2023-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0018_alter_atimeslot_room_alter_atimeslot_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atimeslot',
            name='slot',
            field=models.CharField(max_length=10),
        ),
    ]
