# Generated by Django 4.1.6 on 2023-06-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0019_alter_atimeslot_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='atimeslot',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
