# Generated by Django 4.1.6 on 2023-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0021_atimeslot_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
