# Generated by Django 4.1.6 on 2023-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0023_booking_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='atimeslot',
            name='month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
