# Generated by Django 4.1.6 on 2023-06-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0025_atimeslot_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
