# Generated by Django 4.1.6 on 2023-06-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0026_booking_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
