# Generated by Django 4.1.6 on 2023-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0029_freeslot_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='atimeslot',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
