# Generated by Django 4.1.6 on 2023-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0030_atimeslot_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeslot',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='freeslot',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
