# Generated by Django 4.1.6 on 2023-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0031_freeslot_first_name_freeslot_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeslot',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
