# Generated by Django 4.1.6 on 2023-06-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0032_freeslot_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeslot',
            name='charges',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
