# Generated by Django 4.1.6 on 2023-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0033_freeslot_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeslot',
            name='lock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
